version: "3"
services:
  app-strapi:
    build: .
    environment:
    - ADMIN_JWT_SECRET=xUeC6EljH2yHdI+X1XQSiw
    - API_TOKEN_SALT=SybwM3mvmMOeXCUISqqJCw
    - APP_KEYS=yEkXE2kqkKYniy9F0vu87A==,t2eEkgK+iqPjsj8oVNytfg==,MuEDqElY0s1BFkzxl6re6g==,5Gz+TnQWHXTWFp8yZ4RXnw==
    - CLOUDINARY_KEY=923846922276386
    - CLOUDINARY_NAME=acemc
    - CLOUDINARY_SECRET=AHYBI0MXzqxHiO_K94gMcJX5ahM
    - DATABASE_URL="postgresql://postgres:@172.16.10.101:5432/acewebdb"
    - JWT_SECRET=AXLAw1OsW/Lj8mIZZyRaHQ
    - NODE_ENV=production
    ports:
      - "1337:1337"
    volumes:
      - strapi:/usr/src/app/website/strapi
      
volumes:
  strapi:

    