version: "3"
services:
  app-strapi:
    build: .
    environment:
    - ADMIN_JWT_SECRET=xUeC6EljH2yHdI+X1XQSiw
    - API_TOKEN_SALT=SybwM3mvmMOeXCUISqqJCw
    - APP_KEYS=yEkXE2kqkKYniy9F0vu87A==,t2eEkgK+iqPjsj8oVNytfg==,MuEDqElY0s1BFkzxl6re6g==,5Gz+TnQWHXTWFp8yZ4RXnw==
    - CLOUDINARY_KEY=923846922276386
    - CLOUDINARY_NAME=acemc
    - CLOUDINARY_SECRET=AHYBI0MXzqxHiO_K94gMcJX5ahM
    - DATABASE_URL=postgres://vwqaaytgexcvwr:1d254db1d1acbe10b754d137902781fab035d4c18b2a6977e11af1bb9c1188a6@ec2-3-209-124-113.compute-1.amazonaws.com:5432/d81nbco6i67ldr
    - JWT_SECRET=AXLAw1OsW/Lj8mIZZyRaHQ
    - NODE_ENV=production
    ports:
      - "1337:1337"
    volumes:
      - strapi:/usr/src/app/website/strapi
      
volumes:
  strapi:

    